# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ICEntertainment', '0002_auto_20171007_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='id_author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='id_post',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='post',
            new_name='id_post',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='post',
            new_name='id_post',
        ),
        migrations.AddField(
            model_name='comment',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
